blog/urls.py
from django.urls import path
from .views import blog_list

app_name = "blog"

urlpatterns = [
    path("", blog_list, name="blog"),
]

bookings/urls.py
from django.urls import path

from .views import (
    select_table,
    select_date_time,
    enter_details,
    confirm_booking,
    booking_success,
    booking_failure,
)

from .api_views import (
    get_available_times,
    get_booked_times,
    get_availability_matrix,
    bookings_for_date,
    apply_update_blocks,
)

from .admin_views import (
    booking_availability,
    view_bookings,
)

app_name = "bookings"

urlpatterns = [
    # Booking flow
    path("select-table/", select_table, name="select_table"),
    path("select-date-time/", select_date_time, name="select_date_time"),
    path("enter-details/", enter_details, name="enter_details"),
    path("confirm-booking/", confirm_booking, name="confirm_booking"),
    path("bookings-success/", booking_success, name="booking_success"),
    path("bookings-failure/", booking_failure, name="booking_failure"),

    # API endpoints
    path("get_available_times/", get_available_times, name="get_available_times"),
    path("get_booked_times/", get_booked_times, name="get_booked_times"),
    path("availability_matrix/", get_availability_matrix, name="availability_matrix"),
    path("bookings_by_date/", bookings_for_date, name="bookings_by_date"),
    path("apply_update_blocks/", apply_update_blocks, name="apply_update_blocks"),

    # Admin views
    path("booking_availability/", booking_availability, name="booking_availability"),
    path("view_bookings/", view_bookings, name="view_bookings"),
]

communitea_gaming/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.utils import is_admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('bookings/', include('bookings.urls')),
    path('events/', include('events.urls')),
    path("about/", include("about.urls")),
    path("contact/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("user/is_admin", is_admin, name="is_admin"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/loading-overlay.html
{% load static %}

<div id="loadingOverlay" aria-hidden="true">
    <img class="loading-meeple loading-meeple--red" src="{% static 'images/meeple-svgrepo-com.svg' %}" alt="">
    <img class="loading-meeple loading-meeple--blue" src="{% static 'images/meeple-svgrepo-com.svg' %}" alt="">
    <img class="loading-meeple loading-meeple--yellow" src="{% static 'images/meeple-svgrepo-com.svg' %}" alt="">
</div>

templates/includes/main-nav.html
<ul class="nav-list" role="menubar" aria-label="Main navigation">
  <li class="nav-list-item" role="none">
    <a href="{% url 'events' %}" role="menuitem">What's on</a>
  </li>

  <li class="nav-list-item" role="none">
    <a href="{% url 'bookings:select_table' %}" role="menuitem">Book a table</a>

    {% if request.user.is_authenticated and request.user.is_staff %}
      <ul class="nav-list-sub-list" role="menu" aria-label="Admin booking options">
        <li class="nav-list-sub-list-item" role="none">
          <a href="{% url 'bookings:booking_availability' %}" role="menuitem">Availability</a>
        </li>
        <li class="nav-list-sub-list-item" role="none">
          <a href="{% url 'bookings:view_bookings' %}" role="menuitem">Bookings</a>
        </li>
      </ul>
    {% endif %}
  </li>

  <li class="nav-list-item" role="none">
    <a href="{% url 'about' %}" role="menuitem">About us</a>
  </li>

  <li class="nav-list-item" role="none">
    <a href="{% url 'blog:blog' %}" role="menuitem">Blog</a>
  </li>

  <li class="nav-list-item" role="none">
    <a href="{% url 'contact' %}" role="menuitem">Contact Us</a>
  </li>
</ul>

templates/includes/mobile-nav.html
<!-- can make a separate mobile nav if needed -->